# Google App Engine Configuration for OrbiSEO Frontend
runtime: nodejs18

env_variables:
  NODE_ENV: production
  NEXT_PUBLIC_FIREBASE_API_KEY: AIzaSyBztRu3Cv_GqCZ8eVT_l6LTryQRx42RYQ4
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: studio-7522026757-cda8b.firebaseapp.com
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: studio-7522026757-cda8b
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: studio-7522026757-cda8b.firebasestorage.app
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "989057558837"
  NEXT_PUBLIC_FIREBASE_APP_ID: 1:989057558837:web:f3f42b558e2672f886c47c
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: G-FEH6N1H3MK
  NEXT_PUBLIC_RECAPTCHA_SITE_KEY: 6LeZrPArAAAAAPy3T_UpsOmyINJ0VV6q_hShnX7S
  NEXT_PUBLIC_API_URL: https://api-orbiseo-dot-studio-7522026757-cda8b.uc.r.appspot.com

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301