version: '3.8'

services:
  # Next.js Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "9002:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_AI_CRAWL_URL=http://localhost:8001
    depends_on:
      - backend-main
      - backend-ai-crawl
    restart: unless-stopped
    networks:
      - orbiseo-network

  # Main Python Backend (Port 8000)
  backend-main:
    build:
      context: ./python_backend
      dockerfile: Dockerfile.main
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
      - LOG_LEVEL=INFO
    env_file:
      - .env.production
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    networks:
      - orbiseo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # AI Crawl Backend (Port 8001)
  backend-ai-crawl:
    build:
      context: ./python_backend
      dockerfile: Dockerfile.crawl
    ports:
      - "8001:8001"
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - LOG_LEVEL=INFO
    restart: unless-stopped
    networks:
      - orbiseo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend-main
      - backend-ai-crawl
    restart: unless-stopped
    networks:
      - orbiseo-network

networks:
  orbiseo-network:
    driver: bridge

volumes:
  data:
    driver: local