# Google App Engine Configuration for OrbiSEO Python Backend
service: api-orbiseo
runtime: python311

env_variables:
  HOST: 0.0.0.0
  PORT: 8080
  NODE_ENV: production
  SECRET_KEY: orbiseo-production-secret-2024-gcp
  CORS_ORIGINS: '["https://orbiseo.com", "https://www.orbiseo.com", "https://studio-7522026757-cda8b.uc.r.appspot.com"]'

  # Pinecone Configuration
  PINECONE_API_KEY: pcsk_5tgCig_HMWycqqQtk8ybJxw6nLx2c9TnRgqHAJMTiCGwAY3hZqzc32eDtfQSmunRTVmaz3
  PINECONE_ENVIRONMENT: us-east-1
  PINECONE_INDEX_NAME: orbiseo
  PINECONE_HOST: https://orbiseo-j8k3wcb.svc.aped-4627-b74a.pinecone.io
  PINECONE_METRIC: dotproduct
  PINECONE_CLOUD: aws
  PINECONE_REGION: us-east-1
  PINECONE_CAPACITY_MODE: serverless

  # ML Models
  SENTENCE_TRANSFORMER_MODEL: all-MiniLM-L6-v2
  MODEL_CACHE_DIR: ./data/models
  PINECONE_SPARSE_MODEL: pinecone-sparse-english-v0

  # reCAPTCHA
  RECAPTCHA_SECRET_KEY: your_recaptcha_secret_key_here

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.7

handlers:
- url: /.*
  script: auto
  secure: always