services:
  - type: web
    name: orbiseo-backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        value: us-east-1
      - key: PINECONE_INDEX_NAME
        value: orbiseo
      - key: PINECONE_HOST
        sync: false
      - key: CORS_ORIGINS
        value: '["http://localhost:9002","https://orbiseo1.netlify.app"]'